site_name: Rampant
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - python
    - c
    - c++
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
  nav_style: dark
  title_inly: false
  navigation_depth: 3
  prev_next_buttons_location: bottom
  include_homepage_in_sidebar: true
plugins:
  - search
title: hola
extra_css:
  - css/main.css
extra:
  version: 1.0.0